version: '3.7'
services:
  shinobi:
      image: shinobicctv/shinobi:latest
      environment:
          APP_BRANCH: dev
      ports:
          - "8080:8080/tcp"
      volumes:
          - type: bind
            source: ./data/shinobiStreams
            target: /dev/shm/streams
          - type: bind
            source: ./data/shinobiConfig
            target: /config
          - type: bind
            source: ./data/shinobiCustomAutoLoad
            target: /customAutoLoad
          - type: bind
            source: ./data/shinobiDatabase
            target: /var/lib/mysql
          - type: bind
            source: ./data/shinobiVideos
            target: /opt/shinobi/videos
